version: 2
updates:
  - package-ecosystem: npm
    directory: /keeltrader/apps/web
    target-branch: v2
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 0
    groups:
      web-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - web

  - package-ecosystem: pip
    directory: /keeltrader/apps/api
    target-branch: v2
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 0
    groups:
      api-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - api

  - package-ecosystem: docker
    directory: /keeltrader/apps/web
    target-branch: v2
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 0
    groups:
      web-container-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: /keeltrader/apps/api
    target-branch: v2
    schedule:
      interval: weekly
      day: monday
      time: "10:15"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 0
    groups:
      api-container-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: /keeltrader
    target-branch: v2
    schedule:
      interval: weekly
      day: monday
      time: "10:25"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 0
    groups:
      selfhost-containers:
        patterns:
          - "*"
    labels:
      - dependencies
      - docker

  - package-ecosystem: github-actions
    directory: /
    target-branch: v2
    schedule:
      interval: weekly
      day: monday
      time: "10:30"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 0
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - dependencies
      - github-actions
