ARG API_UNDER_TEST_IMAGE=keeltrader-api:test-overlay
FROM ${API_UNDER_TEST_IMAGE}

ARG PIP_INDEX_URL=https://pypi.org/simple/

ENV PIP_DEFAULT_TIMEOUT=120 \
    PIP_RETRIES=10 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_INDEX_URL=${PIP_INDEX_URL}

USER root
WORKDIR /app/apps/api

RUN pip install --no-cache-dir --prefer-binary -r requirements.txt

USER appuser
WORKDIR /app

CMD ["pytest"]
