name: Bug report
description: Report a bug to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you observe?
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Please redact secrets (API keys, tokens, cookies).

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "OS, Docker, Node, Python versions"
