'use client'

import { Loader2 } from 'lucide-react'
import { useRouter, useSearchParams } from 'next/navigation'
import { Panel, PanelGroup, PanelResizeHandle } from 'react-resizable-panels'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { toast } from 'sonner'

import { Button } from '@/components/ui/button'
import { agentPlatformApi, marketsApi, type FuturesCurve, type FuturesHistory, type FuturesProduct, type MarketUnderlying, type UnderlyingSeries } from '@/lib/api/agent-platform'
import { DataLedger, MarketShell } from '../_components/market-shell'
import { NativeSeriesChart } from '../_components/native-series-chart'

type Field='close'|'settle'|'vol'|'oi';const fieldNames:Record<Field,string>={close:'收盘价',settle:'结算价',vol:'成交量',oi:'持仓量'}
export default function FuturesMarketPage(){
  const router=useRouter(),params=useSearchParams(),product=params.get('product')||'',field=(params.get('field') as Field)||'close'
  const [products,setProducts]=useState<FuturesProduct[]>([]),[history,setHistory]=useState<FuturesHistory|null>(null),[curve,setCurve]=useState<FuturesCurve|null>(null),[underlying,setUnderlying]=useState<MarketUnderlying|null>(null),[underlyingSeries,setUnderlyingSeries]=useState<UnderlyingSeries|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false)
  const select=useCallback((code:string,nextField:Field=field)=>{const q=new URLSearchParams(params.toString());q.set('product',code);q.set('field',nextField);router.replace(`/agent/market/futures?${q}`)},[field,params,router])
  const loadProducts=useCallback(async(refresh=false)=>{refresh?setRefreshing(true):setLoading(true);try{const result=await marketsApi.futuresProducts();setProducts(result.items);if(!product&&result.items[0])select(result.items[0].product_code)}catch(error){toast.error(error instanceof Error?error.message:'期货目录加载失败')}finally{setLoading(false);setRefreshing(false)}},[product,select])
  useEffect(()=>{queueMicrotask(()=>void loadProducts())},[loadProducts])
  useEffect(()=>{if(!product)return;let active=true;Promise.all([marketsApi.futuresHistory(product),marketsApi.futuresCurve(product),marketsApi.futuresUnderlying(product)]).then(async([h,c,u])=>{if(!active)return;setHistory(h);setCurve(c);setUnderlying(u);setUnderlyingSeries(u.series_available&&u.code&&['index','etf','futures_contract'].includes(u.relationship)?await marketsApi.underlyingSeries(u.relationship,u.code):null)}).catch(error=>toast.error(error instanceof Error?error.message:'期货工作区加载失败'));return()=>{active=false}},[product])
  const rows=history?.history||[],current=products.find(item=>item.product_code===product)
  const bring=async()=>{if(!history)return;const snapshot=await agentPlatformApi.createContextSnapshot({resource_type:'futures',resource_id:product,field,visible_start:history.history_meta.start_date,visible_end:history.history_meta.end_date,source:history.history_meta.source,methodology:'主力映射原始历史；合约切换不做复权或人工连续化。'});router.push(`/agent?context_snapshot=${snapshot.id}&context_label=${encodeURIComponent(`${product}·${field}`)}`)}
  return <MarketShell title="期货市场" subtitle="主力轨迹、期限结构与正确底层关系" refreshing={refreshing} onRefresh={()=>void loadProducts(true)} onResearch={history?()=>void bring():undefined} trail={{object:product||'期货品种',asOf:history?.history_meta.end_date,source:history?.history_meta.source}}>
    {loading&&!products.length?<Loading/>:<PanelGroup direction="horizontal" autoSaveId="futures-market-workspace" className="min-h-[calc(100dvh-13rem)] overflow-hidden rounded-xl border bg-card/70">
      <Panel defaultSize={20} minSize={15} maxSize={30}><aside className="h-full overflow-y-auto border-r p-2"><p className="px-2 py-3 text-[10px] font-semibold uppercase tracking-[.18em] text-muted-foreground">期货品种</p>{products.map(item=><button key={item.product_code} onClick={()=>select(item.product_code)} className={`mb-1 w-full rounded-lg px-3 py-2.5 text-left ${item.product_code===product?'bg-[hsl(var(--accent)/.12)] shadow-[inset_2px_0_hsl(var(--copper))]':'hover:bg-secondary'}`}><span className="block text-xs font-medium">{item.product_code} · {item.name}</span><span className="font-data text-[9px] text-muted-foreground">{item.exchange} · {item.mapping_ts_code}</span></button>)}</aside></Panel><Handle/>
      <Panel minSize={42}><main className="h-full space-y-4 overflow-y-auto p-4"><div className="flex gap-2">{(Object.keys(fieldNames) as Field[]).map(key=><Button key={key} size="sm" variant={field===key?'default':'outline'} onClick={()=>select(product,key)}>{fieldNames[key]}</Button>)}</div><DataLedger source={history?.history_meta.source||'tushare.fut_mapping+fut_daily'} start={history?.history_meta.start_date} end={history?.history_meta.end_date} points={history?.history_meta.points} scope="全部可用原始历史；未调整"/><NativeSeriesChart key={`${product}-${field}`} dates={rows.map(row=>row.trade_date)} series={[{key:field,label:fieldNames[field],color:'hsl(var(--accent))',values:rows.map(row=>numberOrNull(row[field]))}]}/>{underlyingSeries&&<section><h2 className="mb-2 font-display text-lg font-semibold">底层标的原始历史 · {underlying?.name}</h2><NativeSeriesChart key={underlyingSeries.code} dates={underlyingSeries.rows.map(row=>row.trade_date)} series={[{key:'close',label:'底层收盘',color:'hsl(var(--copper-foreground))',values:underlyingSeries.rows.map(row=>numberOrNull(row.close))}]}/></section>}</main></Panel><Handle/>
      <Panel defaultSize={25} minSize={19} maxSize={36}><aside className="h-full overflow-y-auto border-l p-4"><h2 className="font-display text-lg font-semibold">合约与底层关系</h2><div className="mt-3 rounded-xl border bg-background/60 p-3 text-xs"><p className="font-medium">{underlying?.name||'待识别'}</p><p className="mt-1 font-data text-[9px] text-muted-foreground">{underlying?.relationship} · {underlying?.code||'无单一价格序列'}</p><p className="mt-3 leading-5 text-muted-foreground">{underlying?.methodology}</p></div><h3 className="mt-5 text-xs font-semibold">当日期限结构 · {curve?.trade_date}</h3><div className="mt-2 space-y-1">{curve?.items.map(item=><div key={item.contract_code} className="grid grid-cols-[1fr_auto] border-b py-2 text-[10px]"><span className="font-data">{item.contract_code}</span><span>{fmt(item.close)} · OI {fmt(item.oi)}</span></div>)}</div><p className="mt-5 text-[10px] text-muted-foreground">当前主力 {current?.mapping_ts_code||'—'}。期货和底层图分开展示，不使用双轴制造视觉因果。</p></aside></Panel>
    </PanelGroup>}
  </MarketShell>
}
const Handle=()=> <PanelResizeHandle className="w-1 bg-border/60 hover:bg-[hsl(var(--copper)/.6)]"/>;const numberOrNull=(value:unknown)=>typeof value==='number'&&Number.isFinite(value)?value:null;const fmt=(value?:number)=>value==null?'—':value.toLocaleString('zh-CN',{maximumFractionDigits:4});const Loading=()=> <div className="grid h-80 place-items-center"><Loader2 className="h-7 w-7 animate-spin"/></div>
