"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { AlertTriangle, ArrowRight, BriefcaseBusiness, CalendarClock, Check, Compass, Flag, Home, Landmark, Loader2, Plus, Route, Save, ShieldCheck, Sparkles, Target, Trash2, Users, WalletCards } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

import { KeelMark, ThemeMenu } from "@/components/keel-brand";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { agentPlatformApi, type HouseholdMember, type SaaPolicyVersion, type SaaTarget, type TaaOverlay, type WealthAggregate, type WealthAssignment, type WealthFrameworkVersion } from "@/lib/api/agent-platform";

const money = new Intl.NumberFormat("zh-CN", { style: "currency", currency: "CNY", maximumFractionDigits: 0 });
const pct = (value: number) => `${(value * 100).toFixed(1)}%`;
const today = () => new Date().toISOString().slice(0, 10);
const addDays = (days: number) => { const value = new Date(); value.setDate(value.getDate() + days); return value.toISOString().slice(0, 10); };
const addYears = (years: number) => { const value = new Date(); value.setFullYear(value.getFullYear() + years); return value.toISOString().slice(0, 10); };
type View = "overview" | "people" | "balance" | "framework" | "saa";

export default function HouseholdWealthPage() {
  const search = useSearchParams();
  const [data, setData] = useState<WealthAggregate>();
  const [frameworks, setFrameworks] = useState<WealthFrameworkVersion[]>([]);
  const [saa, setSaa] = useState<SaaPolicyVersion[]>([]);
  const [taa, setTaa] = useState<TaaOverlay[]>([]);
  const [view, setView] = useState<View>("overview");
  const [loading, setLoading] = useState(true);
  const load = useCallback(async () => {
    const [profile, frameworkResult, saaResult, taaResult] = await Promise.all([agentPlatformApi.wealthProfile(), agentPlatformApi.wealthFrameworkVersions(), agentPlatformApi.saaPolicyVersions(), agentPlatformApi.taaOverlays()]);
    setData(profile); setFrameworks(frameworkResult.items); setSaa(saaResult.items); setTaa(taaResult.items); setLoading(false);
  }, []);
  useEffect(() => { queueMicrotask(() => void load().catch((error) => { setLoading(false); toast.error(error instanceof Error ? error.message : "家庭财富加载失败"); })); }, [load]);
  if (loading || !data) return <div className="grid h-full place-items-center"><Loader2 className="h-6 w-6 animate-spin" /></div>;
  return <div className="flex h-full min-h-0 flex-col overflow-hidden bg-background">
    <header className="research-bearing shrink-0 border-b bg-card/95 shadow-sm"><div className="flex min-h-16 items-center gap-3 px-3 sm:px-5"><div className="hidden border-r pr-4 sm:block"><KeelMark /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><Home className="h-4 w-4 text-[hsl(var(--copper-foreground))]" /><h1 className="font-display text-lg font-semibold">家庭财富配置</h1></div><p className="truncate text-[10px] text-muted-foreground">从家庭现状与目标出发，形成可审计的 SAA 基线与人工 TAA 覆盖层</p></div><Button asChild size="sm" variant="outline"><Link href="/agent/allocation"><Route className="mr-1.5 h-4 w-4" />配置引擎</Link></Button><Button asChild size="sm" variant="outline"><Link href="/agent/opportunities"><Compass className="mr-1.5 h-4 w-4" />机会中心</Link></Button><ThemeMenu /></div>
      <nav className="flex overflow-x-auto border-t px-3 sm:px-5" aria-label="家庭财富工作区">{([["overview","财富总览",Home],["people","成员与目标",Users],["balance","资产负债",WalletCards],["framework","财富框架",Route],["saa","SAA / TAA",Compass]] as const).map(([key,label,Icon]) => <button key={key} onClick={() => setView(key)} className={`relative flex shrink-0 items-center gap-2 px-4 py-3 text-xs ${view === key ? "text-foreground" : "text-muted-foreground hover:text-foreground"}`}><Icon className="h-3.5 w-3.5" />{label}{view === key && <span className="absolute inset-x-3 bottom-0 h-0.5 bg-[hsl(var(--copper-foreground))]" />}</button>)}</nav></header>
    <main className="min-h-0 flex-1 overflow-y-auto p-4 md:p-6">{view === "overview" && <Overview data={data} />}{view === "people" && <PeopleGoals data={data} reload={load} />}{view === "balance" && <BalanceSheet data={data} reload={load} />}{view === "framework" && <Framework data={data} versions={frameworks} reload={load} />}{view === "saa" && <SaaTaa data={data} frameworks={frameworks} saa={saa} taa={taa} opportunitySnapshot={search.get("opportunity_snapshot") || undefined} reload={load} />}</main>
  </div>;
}

function Overview({ data }: { data: WealthAggregate }) { const s = data.framework.summary; return <div className="mx-auto max-w-[1500px] space-y-5"><section className="grid gap-px overflow-hidden rounded-2xl border bg-border sm:grid-cols-2 xl:grid-cols-5"><Metric label="家庭净财富" value={money.format(s.net_wealth_cny)} /><Metric label="可配置金融财富" value={money.format(s.allocatable_wealth_cny)} /><Metric label="安全层需求" value={money.format(s.safety_required_cny)} /><Metric label="市场层可用" value={money.format(s.market_available_cny)} /><Metric label="目标资金缺口" value={money.format(s.goal_funding_gap_cny)} /></section><WealthMap data={data} /><div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><section className="rounded-2xl border bg-card/70 p-5"><div className="flex items-center gap-2"><Users className="h-4 w-4 text-[hsl(var(--copper-foreground))]" /><h2 className="font-display text-xl font-semibold">家庭生命周期</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{data.members.length ? data.members.map((member) => <article key={member.id} className="rounded-xl border bg-background/60 p-4"><div className="flex items-center justify-between"><p className="font-medium">{member.name}</p><Badge variant="outline">{roleName(member.role)}</Badge></div><p className="mt-3 font-data text-2xl">{member.age}<span className="ml-1 text-xs text-muted-foreground">岁</span></p><p className="mt-2 text-[10px] text-muted-foreground">{stageName(member.life_stage)}{member.retirement_age ? ` · 预计 ${member.retirement_age} 岁退休` : " · 尚未设置退休年龄"}</p></article>) : <Empty text="添加本人即可使用；单人家庭拥有完整功能。" />}</div></section><ConflictPanel conflicts={data.framework.conflicts} ready={data.framework.ready} /></div></div>; }

function WealthMap({ data }: { data: WealthAggregate }) { const s = data.framework.summary; return <section className="chart-surface overflow-hidden rounded-2xl border p-5 md:p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-data text-[9px] uppercase tracking-[.22em] text-[hsl(var(--copper-foreground))]">Household wealth bearing</p><h2 className="mt-1 font-display text-2xl font-semibold">家庭财富航图</h2></div><p className="max-w-xl text-[10px] leading-5 text-muted-foreground">先保护家庭责任，再让长期资本进入市场；SAA 固定航向，TAA 只能在允许水域临时偏航。</p></div><div className="mt-6 grid items-center gap-4 lg:grid-cols-[.8fr_auto_1.35fr_auto_1fr]"><MapNode label="可配置财富" value={money.format(s.allocatable_wealth_cny)} icon={WalletCards} accent /><ArrowRight className="mx-auto hidden h-5 w-5 text-[hsl(var(--copper-foreground))] lg:block" /><div className="grid gap-2 sm:grid-cols-3"><MapNode label="安全层" value={money.format(s.safety_required_cny)} icon={ShieldCheck} /><MapNode label="市场层" value={money.format(s.market_available_cny)} icon={Landmark} /><MapNode label="进取上限" value={money.format(s.aspirational_limit_cny)} icon={Sparkles} /></div><ArrowRight className="mx-auto hidden h-5 w-5 text-[hsl(var(--copper-foreground))] lg:block" /><div className="grid gap-2"><MapNode label="核心预算" value={money.format(s.core_budget_cny)} icon={Compass} /><MapNode label="卫星预算" value={money.format(s.satellite_budget_cny)} icon={Target} /></div></div><div className="mt-5 grid gap-px overflow-hidden rounded-xl border bg-border sm:grid-cols-3"><Ledger label="短期桶" value={`0–${data.profile.short_bucket_months}个月`} /><Ledger label="中期桶" value={`${data.profile.short_bucket_months + 1}–${data.profile.medium_bucket_months}个月`} /><Ledger label="长期桶" value={`${data.profile.medium_bucket_months}个月以上`} /></div></section>; }

function PeopleGoals({ data, reload }: { data: WealthAggregate; reload: () => Promise<void> }) {
  const [member, setMember] = useState({ name:"", role:data.members.length ? "dependent" : "self", birth_date:"1990-01-01", retirement_age:60, annual_income:0, income_stability:"stable" });
  const [goal, setGoal] = useState({ name:"", member_id:"", target_amount_cny:500000, target_date:addYears(5), priority:"important", flexibility:"flexible" });
  const saveMember = async () => { await agentPlatformApi.createWealthMember({ ...member, role:member.role as HouseholdMember["role"], income_stability:member.income_stability as HouseholdMember["income_stability"], is_primary:member.role === "self" }); setMember({ ...member, name:"", role:"dependent" }); await reload(); toast.success("家庭成员已添加"); };
  const saveGoal = async () => { await agentPlatformApi.createWealthGoal({ ...goal, member_id:goal.member_id || undefined, priority:goal.priority as "essential"|"important"|"aspirational", flexibility:goal.flexibility as "fixed"|"flexible" }); setGoal({ ...goal, name:"" }); await reload(); toast.success("家庭目标已添加"); };
  return <div className="mx-auto grid max-w-[1500px] gap-5 xl:grid-cols-2"><Editor title="家庭成员" icon={Users}><div className="grid gap-3 sm:grid-cols-2"><Field label="称呼"><Input value={member.name} onChange={(e) => setMember({ ...member, name:e.target.value })} placeholder="本人或家庭成员称呼" /></Field><SelectField label="角色" value={member.role} onChange={(role) => setMember({ ...member, role })} options={[["self","本人"],["partner","伴侣"],["dependent","受抚养人"],["parent","父母"],["other","其他"]]} /><Field label="出生日期"><Input type="date" value={member.birth_date} onChange={(e) => setMember({ ...member, birth_date:e.target.value })} /></Field><Field label="预计退休年龄"><Input type="number" value={member.retirement_age} onChange={(e) => setMember({ ...member, retirement_age:Number(e.target.value) })} /></Field><Field label="年度收入"><Input type="number" value={member.annual_income} onChange={(e) => setMember({ ...member, annual_income:Number(e.target.value) })} /></Field><SelectField label="收入稳定性" value={member.income_stability} onChange={(income_stability) => setMember({ ...member, income_stability })} options={[["stable","稳定"],["variable","波动"],["uncertain","不确定"]]} /></div><Button className="mt-4" disabled={!member.name} onClick={() => void saveMember()}><Plus className="mr-2 h-4 w-4" />添加成员</Button><ItemList items={data.members.map((m) => ({ id:m.id, title:m.name, meta:`${m.age}岁 · ${roleName(m.role)} · ${stageName(m.life_stage)}`, locked:m.role === "self" }))} onDelete={async (id) => { await agentPlatformApi.deleteWealthMember(id); await reload(); }} /></Editor>
    <Editor title="家庭目标" icon={Flag}><div className="grid gap-3 sm:grid-cols-2"><Field label="目标名称"><Input value={goal.name} onChange={(e) => setGoal({ ...goal, name:e.target.value })} placeholder="养老、教育、购房…" /></Field><SelectField label="关联成员" value={goal.member_id} onChange={(member_id) => setGoal({ ...goal, member_id })} options={[["","全家庭"], ...data.members.map((m) => [m.id,m.name] as [string,string])]} /><Field label="目标金额"><Input type="number" value={goal.target_amount_cny} onChange={(e) => setGoal({ ...goal, target_amount_cny:Number(e.target.value) })} /></Field><Field label="目标日期"><Input type="date" value={goal.target_date} onChange={(e) => setGoal({ ...goal, target_date:e.target.value })} /></Field><SelectField label="优先级" value={goal.priority} onChange={(priority) => setGoal({ ...goal, priority })} options={[["essential","必须保障"],["important","重要目标"],["aspirational","进取目标"]]} /><SelectField label="金额弹性" value={goal.flexibility} onChange={(flexibility) => setGoal({ ...goal, flexibility })} options={[["fixed","固定"],["flexible","可调整"]]} /></div><Button className="mt-4" disabled={!goal.name} onClick={() => void saveGoal()}><Plus className="mr-2 h-4 w-4" />添加目标</Button><ItemList items={data.goals.map((g) => ({ id:g.id, title:g.name, meta:`${bucketName(g.bucket)} · 缺口 ${money.format(g.funding_gap_cny)} · 覆盖 ${pct(g.coverage_ratio)}` }))} onDelete={async (id) => { await agentPlatformApi.deleteWealthGoal(id); await reload(); }} /></Editor></div>;
}

function BalanceSheet({ data, reload }: { data: WealthAggregate; reload: () => Promise<void> }) {
  const [asset, setAsset] = useState({ name:"", category:"financial", value_cny:100000, liquidity:"liquid", allocatable:true });
  const [liability, setLiability] = useState({ name:"", category:"mortgage", balance_cny:0, monthly_payment_cny:0 });
  const saveAsset = async () => { await agentPlatformApi.createWealthAsset({ ...asset, liquidity:asset.liquidity as "liquid"|"limited"|"illiquid" }); setAsset({ ...asset, name:"" }); await reload(); toast.success("资产已添加"); };
  const saveLiability = async () => { await agentPlatformApi.createWealthLiability(liability); setLiability({ ...liability, name:"" }); await reload(); toast.success("负债已添加"); };
  return <div className="mx-auto grid max-w-[1500px] gap-5 xl:grid-cols-2"><Editor title="家庭资产" icon={WalletCards}><div className="grid gap-3 sm:grid-cols-2"><Field label="资产名称"><Input value={asset.name} onChange={(e) => setAsset({ ...asset, name:e.target.value })} /></Field><SelectField label="资产类别" value={asset.category} onChange={(category) => setAsset({ ...asset, category })} options={[["cash","现金"],["financial","金融资产"],["real_estate","房产"],["business","企业股权"],["pension","养老金"],["insurance","保险现金价值"],["other","其他"]]} /><Field label="人民币估值"><Input type="number" value={asset.value_cny} onChange={(e) => setAsset({ ...asset, value_cny:Number(e.target.value) })} /></Field><SelectField label="流动性" value={asset.liquidity} onChange={(liquidity) => setAsset({ ...asset, liquidity, allocatable:liquidity !== "illiquid" })} options={[["liquid","流动"],["limited","有限流动"],["illiquid","非流动"]]} /></div><Button className="mt-4" disabled={!asset.name} onClick={() => void saveAsset()}><Plus className="mr-2 h-4 w-4" />添加资产</Button><ItemList items={data.assets.map((a) => ({ id:a.id, title:a.name, meta:`${money.format(a.value_cny)} · ${liquidityName(a.liquidity)}${a.allocatable ? " · 可配置" : ""}` }))} onDelete={async (id) => { await agentPlatformApi.deleteWealthAsset(id); await reload(); }} /></Editor>
    <Editor title="家庭负债" icon={BriefcaseBusiness}><div className="grid gap-3 sm:grid-cols-2"><Field label="负债名称"><Input value={liability.name} onChange={(e) => setLiability({ ...liability, name:e.target.value })} /></Field><SelectField label="负债类别" value={liability.category} onChange={(category) => setLiability({ ...liability, category })} options={[["mortgage","房贷"],["consumer","消费贷款"],["business","经营负债"],["other","其他"]]} /><Field label="剩余负债"><Input type="number" value={liability.balance_cny} onChange={(e) => setLiability({ ...liability, balance_cny:Number(e.target.value) })} /></Field><Field label="月度偿还"><Input type="number" value={liability.monthly_payment_cny} onChange={(e) => setLiability({ ...liability, monthly_payment_cny:Number(e.target.value) })} /></Field></div><Button className="mt-4" disabled={!liability.name} onClick={() => void saveLiability()}><Plus className="mr-2 h-4 w-4" />添加负债</Button><ItemList items={data.liabilities.map((l) => ({ id:l.id, title:l.name, meta:`${money.format(l.balance_cny)} · 月还 ${money.format(l.monthly_payment_cny)}` }))} onDelete={async (id) => { await agentPlatformApi.deleteWealthLiability(id); await reload(); }} /></Editor></div>;
}

function Framework({ data, versions, reload }: { data: WealthAggregate; versions: WealthFrameworkVersion[]; reload: () => Promise<void> }) {
  const [settings, setSettings] = useState({ annual_essential_spending:Number(data.profile.annual_essential_spending), short_bucket_months:data.profile.short_bucket_months, medium_bucket_months:data.profile.medium_bucket_months, aspirational_cap:Number(data.profile.aspirational_cap), satellite_cap:Number(data.profile.satellite_cap) });
  const save = async () => { await agentPlatformApi.updateWealthProfile(settings); await reload(); toast.success("财富框架参数已保存"); };
  const version = async () => { const result = await agentPlatformApi.createWealthFrameworkVersion(); await reload(); toast.success(`已保存财富框架 v${result.version}`); };
  return <div className="mx-auto max-w-[1500px] space-y-5"><div className="grid gap-5 xl:grid-cols-[.7fr_1.3fr]"><Editor title="框架边界" icon={Route}><div className="grid gap-3"><Field label="年度必要支出"><Input type="number" value={settings.annual_essential_spending} onChange={(e) => setSettings({ ...settings, annual_essential_spending:Number(e.target.value) })} /></Field><Field label="短期桶（月）"><Input type="number" value={settings.short_bucket_months} onChange={(e) => setSettings({ ...settings, short_bucket_months:Number(e.target.value) })} /></Field><Field label="中期桶（月）"><Input type="number" value={settings.medium_bucket_months} onChange={(e) => setSettings({ ...settings, medium_bucket_months:Number(e.target.value) })} /></Field><Field label="进取层上限（%）"><Input type="number" value={settings.aspirational_cap*100} onChange={(e) => setSettings({ ...settings, aspirational_cap:Number(e.target.value)/100 })} /></Field><Field label="卫星上限（%）"><Input type="number" value={settings.satellite_cap*100} onChange={(e) => setSettings({ ...settings, satellite_cap:Number(e.target.value)/100 })} /></Field></div><Button className="mt-4" onClick={() => void save()}><Save className="mr-2 h-4 w-4" />保存边界</Button></Editor><div className="space-y-5"><WealthMap data={data} /><ConflictPanel conflicts={data.framework.conflicts} ready={data.framework.ready} /></div></div><AssignmentEditor data={data} reload={reload} /><section className="rounded-2xl border bg-card/70 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-xl font-semibold">不可变财富框架</h2><p className="mt-1 text-[10px] text-muted-foreground">保存成员、资产负债、目标、期限桶与三层财富的当前快照。</p></div><Button disabled={!data.framework.ready} onClick={() => void version()}><Check className="mr-2 h-4 w-4" />确认新版本</Button></div><VersionList versions={versions.map((v) => ({ id:v.id, title:`财富框架 v${v.version}`, meta:`${money.format(v.summary.net_wealth_cny)} · ${new Date(v.created_at).toLocaleString("zh-CN")}` }))} /></section></div>;
}

function AssignmentEditor({ data, reload }: { data: WealthAggregate; reload: () => Promise<void> }) {
  const [items, setItems] = useState<WealthAssignment[]>(data.assignments.map(({ id: _id, ...item }) => item));
  const [draft, setDraft] = useState({ asset_id:data.assets[0]?.id || "", destination:data.goals[0] ? `goal:${data.goals[0].id}:market` : "layer:safety", amount_cny:0 });
  const add = () => {
    const [kind, key, goalLayer] = draft.destination.split(":");
    const next: WealthAssignment = { asset_id:draft.asset_id, amount_cny:draft.amount_cny };
    if (kind === "goal") { next.goal_id = key; next.layer = goalLayer as WealthAssignment["layer"]; }
    else next.layer = key as WealthAssignment["layer"];
    setItems([...items, next]); setDraft({ ...draft, amount_cny:0 });
  };
  const save = async () => { await agentPlatformApi.replaceWealthAssignments(items); await reload(); toast.success("资金指定已保存"); };
  const assetName = (id:string) => data.assets.find((item) => item.id === id)?.name || "未知资产";
  const destinationName = (item:WealthAssignment) => item.goal_id ? `${data.goals.find((goal) => goal.id === item.goal_id)?.name || "未知目标"} · ${layerName(item.layer || "")}` : layerName(item.layer || "");
  return <section className="rounded-2xl border bg-card/70 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-display text-xl font-semibold">资金指定</h2><p className="mt-1 text-[10px] text-muted-foreground">把资产金额指定给目标与财富层；同一资产可拆分，合计不得超过当前估值。</p></div><Button variant="outline" disabled={!data.assets.length} onClick={() => void save()}><Save className="mr-2 h-4 w-4" />保存全部指定</Button></div>
    <div className="mt-5 grid gap-3 md:grid-cols-[1fr_1.4fr_1fr_auto]"><SelectField label="资金来源" value={draft.asset_id} onChange={(asset_id)=>setDraft({...draft,asset_id})} options={data.assets.map((item)=>[item.id,`${item.name} · ${money.format(item.value_cny)}`])} /><SelectField label="目标或财富层" value={draft.destination} onChange={(destination)=>setDraft({...draft,destination})} options={[["layer:safety","安全层"],["layer:market","市场层"],["layer:aspirational","进取层"],...data.goals.flatMap((goal)=>[[`goal:${goal.id}:safety`,`${goal.name} · 安全层`],[`goal:${goal.id}:market`,`${goal.name} · 市场层`],[`goal:${goal.id}:aspirational`,`${goal.name} · 进取层`]] as Array<[string,string]>)]} /><Field label="指定金额"><Input type="number" min="0" value={draft.amount_cny} onChange={(e)=>setDraft({...draft,amount_cny:Number(e.target.value)})} /></Field><Button className="self-end" disabled={!draft.asset_id || draft.amount_cny <= 0} onClick={add}><Plus className="mr-2 h-4 w-4" />加入</Button></div>
    <div className="mt-4 space-y-2">{items.map((item,index)=><div key={`${item.asset_id}-${item.goal_id || item.layer}-${index}`} className="flex items-center gap-3 rounded-xl border bg-background/55 p-3"><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium">{assetName(item.asset_id)} → {destinationName(item)}</p><p className="mt-1 font-data text-[9px] text-muted-foreground">{money.format(item.amount_cny)}</p></div><Button size="icon" variant="ghost" aria-label="移除资金指定" onClick={()=>setItems(items.filter((_,itemIndex)=>itemIndex!==index))}><Trash2 className="h-3.5 w-3.5" /></Button></div>)}{!items.length&&<Empty text="尚未指定资金；可先按安全层、市场层、进取层分配，再细化到家庭目标。" />}</div>
  </section>;
}

function SaaTaa({ data, frameworks, saa, taa, opportunitySnapshot, reload }: { data: WealthAggregate; frameworks: WealthFrameworkVersion[]; saa: SaaPolicyVersion[]; taa: TaaOverlay[]; opportunitySnapshot?: string; reload: () => Promise<void> }) {
  const latestFramework = frameworks[0], confirmed = saa.find((item) => item.status === "confirmed");
  const [targets, setTargets] = useState<SaaTarget[]>(useMemo(() => defaultTargets(data), [data]));
  const [form, setForm] = useState({ title:opportunitySnapshot ? "机会证据战术草案" : "临时战术偏离", rationale:"", plusKey:"market_core", minusKey:"market_satellite", delta:.02, starts_at:today(), review_at:addDays(30), expires_at:addDays(90) });
  const plusTarget = confirmed?.targets.find((item)=>item.key===form.plusKey), minusTarget = confirmed?.targets.find((item)=>item.key===form.minusKey);
  const maxTaaDelta = plusTarget && minusTarget ? Math.max(0,Math.min(plusTarget.max_weight-plusTarget.target_weight,minusTarget.target_weight-minusTarget.min_weight)) : 0;
  const createSaa = async () => { if (!latestFramework) return; await agentPlatformApi.createSaaPolicyVersion({ framework_version_id:latestFramework.id, name:`家庭长期战略配置 ${today()}`, effective_date:today(), review_date:addYears(1), targets }); await reload(); toast.success("SAA草案已保存"); };
  const createTaa = async () => { if (!confirmed || form.delta <= 0 || form.delta > maxTaaDelta) return; await agentPlatformApi.createTaaOverlay({ saa_version_id:confirmed.id, opportunity_snapshot_id:opportunitySnapshot, title:form.title, deltas:{ [form.plusKey]:form.delta, [form.minusKey]:-form.delta }, rationale:form.rationale, starts_at:form.starts_at, review_at:form.review_at, expires_at:form.expires_at }); await reload(); toast.success("TAA草案已创建，尚未生效"); };
  const total = targets.reduce((sum,item) => sum+item.target_weight,0);
  return <div className="mx-auto grid max-w-[1500px] gap-5 xl:grid-cols-[1.2fr_.8fr]"><section className="rounded-2xl border bg-card/70 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-data text-[9px] uppercase tracking-[.2em] text-[hsl(var(--copper-foreground))]">Strategic bearing</p><h2 className="mt-1 font-display text-2xl font-semibold">SAA 长期基线</h2><p className="mt-2 text-[10px] text-muted-foreground">年龄、家庭责任和期限用于约束说明，不套用机械股债公式。</p></div><Badge variant={Math.abs(total-1)<1e-6 ? "outline":"destructive"}>合计 {pct(total)}</Badge></div>{!latestFramework && <Empty text="先在“财富框架”中确认一个不可变版本。" />}<div className="mt-5 space-y-2">{targets.map((item,index) => <div key={item.key} className="grid items-center gap-2 rounded-xl border bg-background/60 p-3 sm:grid-cols-[1fr_110px_110px_110px]"><div><p className="text-xs font-medium">{item.label}</p><p className="text-[9px] text-muted-foreground">{layerName(item.layer)}</p></div>{(["min_weight","target_weight","max_weight"] as const).map((key) => <Field key={key} label={{min_weight:"下限 %",target_weight:"目标 %",max_weight:"上限 %"}[key]}><Input type="number" disabled={item.layer === "safety" && key !== "target_weight"} value={(item[key]*100).toFixed(1)} onChange={(e) => { const value=Number(e.target.value)/100, next=[...targets]; next[index]={...item,[key]:value}; if(item.layer === "safety" && key === "target_weight") next[index]={...next[index],min_weight:value,max_weight:value}; setTargets(next); }} /></Field>)}</div>)}</div><Button className="mt-5" disabled={!latestFramework || Math.abs(total-1)>1e-6} onClick={() => void createSaa()}><Save className="mr-2 h-4 w-4" />保存 SAA 草案</Button><div className="mt-6 border-t pt-5"><h3 className="font-display text-lg font-semibold">SAA 版本</h3><div className="mt-3 space-y-2">{saa.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-xl border bg-background/55 p-3"><div className="min-w-0 flex-1"><p className="text-xs font-medium">v{item.version} · {item.name}</p><p className="mt-1 text-[9px] text-muted-foreground">{item.effective_date} 生效 · {item.review_date} 复核</p></div><Badge variant="outline">{statusName(item.status)}</Badge>{item.status === "draft" && <Button size="sm" onClick={async()=>{await agentPlatformApi.confirmSaaPolicyVersion(item.id);await reload();}}>确认</Button>}</div>)}</div></div></section>
    <section className="rounded-2xl border bg-card/70 p-5"><div className="flex items-center gap-2"><CalendarClock className="h-4 w-4 text-[hsl(var(--copper-foreground))]" /><h2 className="font-display text-2xl font-semibold">TAA 人工覆盖层</h2></div><p className="mt-2 text-[10px] leading-5 text-muted-foreground">只允许在已确认 SAA 区间内临时偏离；权重守恒，安全层锁定，到期不自动续期。</p>{opportunitySnapshot && <div className="mt-3 rounded-xl border border-[hsl(var(--copper)/.4)] bg-[hsl(var(--accent)/.08)] p-3 text-[10px]">已带入机会中心快照；它只作为证据，不自动生成仓位。</div>}{confirmed ? <div className="mt-5 space-y-3"><Field label="草案名称"><Input value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})} /></Field><Field label="判断与依据"><Input value={form.rationale} onChange={(e)=>setForm({...form,rationale:e.target.value})} placeholder="为什么需要暂时偏离 SAA？" /></Field><div className="grid gap-3 sm:grid-cols-2"><SelectField label="增加" value={form.plusKey} onChange={(plusKey)=>setForm({...form,plusKey})} options={confirmed.targets.filter(t=>t.layer!=="safety").map(t=>[t.key,t.label])} /><SelectField label="减少" value={form.minusKey} onChange={(minusKey)=>setForm({...form,minusKey})} options={confirmed.targets.filter(t=>t.layer!=="safety").map(t=>[t.key,t.label])} /><Field label={`偏离幅度 % · 上限 ${(maxTaaDelta*100).toFixed(1)}%`}><Input type="number" min="0" max={maxTaaDelta*100} value={form.delta*100} onChange={(e)=>setForm({...form,delta:Number(e.target.value)/100})} /></Field><Field label="生效日期"><Input type="date" value={form.starts_at} onChange={(e)=>setForm({...form,starts_at:e.target.value})} /></Field><Field label="复核日期"><Input type="date" value={form.review_at} onChange={(e)=>setForm({...form,review_at:e.target.value})} /></Field><Field label="失效日期"><Input type="date" value={form.expires_at} onChange={(e)=>setForm({...form,expires_at:e.target.value})} /></Field></div><Button disabled={!form.rationale || form.plusKey===form.minusKey || form.delta<=0 || form.delta>maxTaaDelta} onClick={() => void createTaa()}><Plus className="mr-2 h-4 w-4" />创建 TAA 草案</Button></div> : <Empty text="确认一个 SAA 版本后，才能建立 TAA。" />}<div className="mt-6 space-y-2">{taa.map((item) => <article key={item.id} className="rounded-xl border bg-background/55 p-3"><div className="flex items-center justify-between gap-2"><p className="text-xs font-medium">{item.title}</p><Badge variant="outline">{statusName(item.status)}</Badge></div><p className="mt-2 text-[10px] leading-5 text-muted-foreground">{item.rationale}</p><p className="mt-2 font-data text-[9px]">复核 {item.review_at} · 失效 {item.expires_at}</p><div className="mt-3 flex gap-2">{item.status === "draft" && <Button size="sm" onClick={async()=>{await agentPlatformApi.confirmTaaOverlay(item.id);await reload();}}>人工确认</Button>}{item.status === "confirmed" && <Button size="sm" variant="outline" onClick={async()=>{await agentPlatformApi.closeTaaOverlay(item.id);await reload();}}>提前关闭</Button>}</div></article>)}</div></section></div>;
}

function defaultTargets(data: WealthAggregate): SaaTarget[] { const s=data.framework.summary,total=Math.max(1,s.allocatable_wealth_cny),safety=Math.min(1,s.safety_required_cny/total),aspirational=Math.min(Number(data.profile.aspirational_cap),Math.max(0,1-safety)*.1),market=Math.max(0,1-safety-aspirational),satellite=market*Number(data.profile.satellite_cap),core=market-satellite; return [{key:"safety",label:"安全层",layer:"safety",target_weight:safety,min_weight:safety,max_weight:safety},{key:"market_core",label:"市场核心",layer:"market",target_weight:core,min_weight:Math.max(0,core-.1),max_weight:Math.min(1,core+.1)},{key:"market_satellite",label:"市场卫星",layer:"market",target_weight:satellite,min_weight:0,max_weight:Math.min(1,satellite+.1)},{key:"aspirational",label:"进取层",layer:"aspirational",target_weight:aspirational,min_weight:0,max_weight:Number(data.profile.aspirational_cap)}]; }
function Metric({label,value}:{label:string;value:string}){return <div className="bg-card/90 p-4"><p className="text-[9px] text-muted-foreground">{label}</p><p className="mt-2 font-data text-lg font-medium">{value}</p></div>}
function MapNode({label,value,icon:Icon,accent}:{label:string;value:string;icon:typeof Home;accent?:boolean}){return <div className={`rounded-xl border p-4 ${accent?"border-[hsl(var(--copper)/.6)] bg-[hsl(var(--accent)/.1)]":"bg-card/85"}`}><Icon className="h-4 w-4 text-[hsl(var(--copper-foreground))]"/><p className="mt-3 text-[9px] text-muted-foreground">{label}</p><p className="mt-1 font-data text-sm font-medium">{value}</p></div>}
function Ledger({label,value}:{label:string;value:string}){return <div className="bg-card/90 px-4 py-3"><p className="text-[9px] text-muted-foreground">{label}</p><p className="mt-1 font-data text-[10px]">{value}</p></div>}
function ConflictPanel({conflicts,ready}:{conflicts:string[];ready:boolean}){return <section className={`rounded-2xl border p-5 ${ready?"border-emerald-500/35 bg-emerald-500/[.05]":"border-amber-500/40 bg-amber-500/[.05]"}`}><div className="flex items-center gap-2">{ready?<Check className="h-4 w-4 text-emerald-600"/>:<AlertTriangle className="h-4 w-4 text-amber-600"/>}<h2 className="font-display text-lg font-semibold">{ready?"框架可以确认":"需要补充或修正"}</h2></div><div className="mt-3 space-y-2 text-[10px] leading-5 text-muted-foreground">{conflicts.length?conflicts.map(item=><p key={item}>· {item}</p>):<p>成员、目标与资金边界没有发现硬冲突。</p>}</div></section>}
function Editor({title,icon:Icon,children}:{title:string;icon:typeof Home;children:React.ReactNode}){return <section className="rounded-2xl border bg-card/70 p-5"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-[hsl(var(--copper-foreground))]"/><h2 className="font-display text-xl font-semibold">{title}</h2></div><div className="mt-5">{children}</div></section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-[9px] text-muted-foreground">{label}</span>{children}</label>}
function SelectField({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:Array<readonly [string,string]>}){return <Field label={label}><select className="h-10 w-full rounded-md border bg-background px-3 text-xs" value={value} onChange={e=>onChange(e.target.value)}>{options.map(([key,text])=><option key={key} value={key}>{text}</option>)}</select></Field>}
function ItemList({items,onDelete}:{items:Array<{id:string;title:string;meta:string;locked?:boolean}>;onDelete:(id:string)=>Promise<void>}){return <div className="mt-5 space-y-2">{items.map(item=><div key={item.id} className="flex items-center gap-3 rounded-xl border bg-background/55 p-3"><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium">{item.title}</p><p className="mt-1 text-[9px] text-muted-foreground">{item.meta}</p></div>{!item.locked&&<Button size="icon" variant="ghost" aria-label={`删除 ${item.title}`} onClick={()=>void onDelete(item.id)}><Trash2 className="h-3.5 w-3.5"/></Button>}</div>)}{!items.length&&<Empty text="尚无记录，从上方添加第一项。"/>}</div>}
function VersionList({versions}:{versions:Array<{id:string;title:string;meta:string}>}){return <div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{versions.map(item=><div key={item.id} className="rounded-xl border bg-background/55 p-3"><p className="text-xs font-medium">{item.title}</p><p className="mt-2 font-data text-[9px] text-muted-foreground">{item.meta}</p></div>)}{!versions.length&&<Empty text="尚未确认财富框架版本。"/>}</div>}
function Empty({text}:{text:string}){return <div className="mt-4 rounded-xl border border-dashed p-5 text-center text-[10px] leading-5 text-muted-foreground">{text}</div>}
const roleName=(v:string)=>({self:"本人",partner:"伴侣",dependent:"受抚养人",parent:"父母",other:"其他"}[v]||v),stageName=(v:string)=>({accumulation:"财富积累期",transition:"退休过渡期",retired:"退休期",unspecified:"阶段待完善"}[v]||v),bucketName=(v:string)=>({short:"短期桶",medium:"中期桶",long:"长期桶"}[v]||v),liquidityName=(v:string)=>({liquid:"流动",limited:"有限流动",illiquid:"非流动"}[v]||v),layerName=(v:string)=>({safety:"安全层",market:"市场层",aspirational:"进取层"}[v]||v),statusName=(v:string)=>({draft:"草案",confirmed:"已确认",superseded:"已取代",closed:"已关闭",expired:"已过期"}[v]||v);
