"use client";

import dynamic from "next/dynamic";
import { useRouter, useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";

import { DashboardPage, EmptyPanel, MetricCard, MiniLine, Panel, SectionTitle, StatusDot } from "@/components/agentos/dashboard-ui";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { agentPlatformApi, marketsApi, type MacroMarketSnapshot, type MarketCapabilities, type MarketCapitalSnapshot } from "@/lib/api/agent-platform";
import { useI18n } from "@/lib/i18n/provider";

const RatesDrilldown = dynamic(() => import("@/components/agentos/market-drilldowns").then((module) => module.RatesDrilldown));
const FuturesDrilldown = dynamic(() => import("@/components/agentos/market-drilldowns").then((module) => module.FuturesDrilldown));
const OptionsDrilldown = dynamic(() => import("@/components/agentos/market-drilldowns").then((module) => module.OptionsDrilldown));
type TopTab = "market" | "macro";
const marketViews = ["overview", "valuation", "correlation", "factors", "capital", "futures", "options"];
const macroViews = ["dashboard", "rates"];

export default function MarketPage() {
  const params = useSearchParams(); const router = useRouter(); const { locale, formatCurrency, formatNumber } = useI18n();
  const rawTab = params.get("tab");
  const aliasView = rawTab && !["market", "macro"].includes(rawTab) ? rawTab : null;
  const tab: TopTab = rawTab === "macro" || aliasView === "rates" ? "macro" : "market";
  const requestedView = params.get("view") || aliasView || (tab === "macro" ? "dashboard" : "overview");
  const view = (tab === "market" ? marketViews : macroViews).includes(requestedView) ? requestedView : (tab === "macro" ? "dashboard" : "overview");
  const [capital, setCapital] = useState<MarketCapitalSnapshot | null>(null); const [macro, setMacro] = useState<MacroMarketSnapshot | null>(null); const [capabilities, setCapabilities] = useState<MarketCapabilities | null>(null);
  useEffect(() => { void Promise.allSettled([marketsApi.capital(), agentPlatformApi.macroMarket(), marketsApi.capabilities()]).then(([a, b, c]) => { if (a.status === "fulfilled") setCapital(a.value); if (b.status === "fulfilled") setMacro(b.value); if (c.status === "fulfilled") setCapabilities(c.value); }); }, []);
  useEffect(() => { if (!aliasView && requestedView === view) return; const next = new URLSearchParams(params.toString()); next.set("tab", tab); next.set("view", view); router.replace(`/agent/market?${next}`); }, [aliasView, params, requestedView, router, tab, view]);
  const navigate = (nextTab: TopTab, nextView?: string) => { const next = new URLSearchParams(params.toString()); next.set("tab", nextTab); next.set("view", nextView || (nextTab === "macro" ? "dashboard" : "overview")); router.replace(`/agent/market?${next}`); };
  const period = ["1M", "3M", "1Y", "3Y"].includes(params.get("period") || "") ? params.get("period")! : "1Y"; const window = period === "1M" ? 22 : period === "3M" ? 66 : period === "3Y" ? 756 : 252;
  const history = useMemo(() => (capital?.history ?? []).slice(-window), [capital, window]); const macroRows = useMemo(() => Object.entries(macro?.series ?? {}), [macro]); const breadth = capital?.breadth;
  return <DashboardPage>
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><MetricCard label="MARKET TURNOVER" value={capital?.liquidity.turnover_cny ? formatCurrency(capital.liquidity.turnover_cny, "CNY") : "—"} note={capital?.as_of || (locale === "zh" ? "数据不可用" : "Unavailable")} color="text-agent-up" /><MetricCard label="ADVANCE RATIO" value={breadth?.advance_ratio != null ? `${(breadth.advance_ratio * (breadth.advance_ratio <= 1 ? 100 : 1)).toFixed(1)}%` : "—"} note={breadth ? `${breadth.advances} / ${breadth.declines}` : "—"} color="text-agent-mint" /><MetricCard label="CAPITAL FLOW" value={capital?.etf_flows.available ? formatCurrency(capital.etf_flows.estimated_net_flow_cny || 0, "CNY") : "—"} note={capital?.etf_flows.note || (locale === "zh" ? "资金流缺口明确展示" : "Flow gaps stay explicit")} color="text-agent-amber" /><MetricCard label="MACRO SERIES" value={formatNumber(macroRows.filter(([, item]) => item.available).length)} note={`${macroRows.length} ${locale === "zh" ? "项正式序列" : "formal series"}`} color="text-agent-blue" /></div>
    <Tabs value={tab} onValueChange={(value) => navigate(value as TopTab)} className="flex flex-col gap-3"><TabsList className="h-auto w-fit border border-agent-border bg-agent-chrome p-1 lg:hidden"><TabsTrigger value="market">{locale === "zh" ? "大盘 · 行业 · 资金流" : "Market · Sectors · Flows"}</TabsTrigger><TabsTrigger value="macro">{locale === "zh" ? "宏观数据" : "Macro Data"}</TabsTrigger></TabsList>
      <TabsContent value="market" className="mt-0 space-y-3"><Secondary items={[["overview", "大盘与行业"], ["valuation", "估值分位"], ["correlation", "相关性"], ["factors", "因子与拥挤"], ["capital", "资金流"], ["futures", "期货"], ["options", "期权"]]} value={view} onChange={(item) => navigate("market", item)} />
        {view === "overview" ? <div className="grid gap-3 xl:grid-cols-[1.25fr_.75fr]"><Panel><SectionTitle title={locale === "zh" ? "大盘成交与市场广度" : "Market Turnover & Breadth"} en="BROAD MARKET" />{history.length ? <div className="h-[300px]"><MiniLine values={history.map((item) => item.turnover_cny)} color="var(--agent-up)" height={100} /></div> : <Gap title="大盘历史不可用" detail="等待 Tushare 原子发布；不使用模拟指数曲线。" />}</Panel><Panel><SectionTitle title={locale === "zh" ? "行业截面" : "Sector Cross-section"} en="SW INDUSTRIES" /><Gap title="申万行情不可用" detail="sw_daily 当前无正式权限，因此行业涨跌、估值与资金流矩阵保持不可用。" /></Panel></div> : null}
        {view === "valuation" ? <Panel><SectionTitle title="估值分位矩阵" en="PE / PB PERCENTILES" /><Gap title="统一估值分位尚未发布" detail="daily_basic 与申万行情不可用；不以静态 PE、指数代理或原型模拟值代替历史分位。" /></Panel> : null}
        {view === "correlation" ? <Panel><SectionTitle title="跨资产相关性" en="ALIGNED RETURNS" /><Gap title="同频正式收益序列不足" detail="只有频率、截至日和 publication 版本一致时才计算相关矩阵。" /></Panel> : null}
        {view === "factors" ? <div className="grid gap-3 xl:grid-cols-2"><Panel><SectionTitle title="因子收益" en="VALUE / MOMENTUM / QUALITY" /><Gap title="因子截面未正式发布" detail="因子收益和 IC 历史不会由示例评分补位。" /></Panel><Panel><SectionTitle title="拥挤度观测" en="OBSERVED PROXIES" /><div className="divide-y divide-agent-border">{[["TOP 20 TURNOVER", capital?.liquidity.top20_turnover_share], ["TOP 50 TURNOVER", capital?.liquidity.top50_turnover_share], ["ETF FLOW COVERAGE", capital?.etf_flows.coverage_ratio], ["ADVANCE RATIO", breadth?.advance_ratio]].map(([name, value]) => <div key={String(name)} className="grid grid-cols-[160px_1fr_64px] gap-3 py-3 text-[10px]"><span className="font-data text-agent-dim">{name}</span><div className="h-1.5 rounded bg-agent-border"><span className="block h-full rounded bg-agent-mint" style={{ width: `${Math.min(100, Number(value || 0) * (Number(value || 0) <= 1 ? 100 : 1))}%` }} /></div><span className="text-right font-data text-agent-muted">{value != null ? `${(Number(value) * (Number(value) <= 1 ? 100 : 1)).toFixed(1)}%` : "—"}</span></div>)}</div></Panel></div> : null}
        {view === "capital" ? <div className="grid gap-3 xl:grid-cols-2"><Panel><SectionTitle title="ETF 资金流" en="ESTIMATED FROM SHARES" />{capital?.etf_flows.available ? <div><p className="font-data text-3xl text-agent-up">{formatCurrency(capital.etf_flows.estimated_net_flow_cny || 0, "CNY")}</p><p className="mt-4 text-xs leading-6 text-agent-muted">{capital.etf_flows.note}</p></div> : <Gap title="ETF 资金流不可用" detail={capital?.etf_flows.note || "等待正式份额快照。"} />}</Panel><Panel><SectionTitle title="股票资金流与北向" en="STOCK / HK HOLD" /><Gap title="正式资金流覆盖不足" detail="stock_moneyflow 与 hk_hold 当前不可用；跟踪页不会用 ETF 流或新闻数字冒充。" /></Panel></div> : null}
        {view === "futures" ? <FuturesDrilldown /> : null}{view === "options" ? <OptionsDrilldown /> : null}
      </TabsContent>
      <TabsContent value="macro" className="mt-0 space-y-3"><Secondary items={[["dashboard", "宏观面板"], ["rates", "利率与债券"]]} value={view} onChange={(item) => navigate("macro", item)} />{view === "dashboard" ? <div className="grid gap-3 xl:grid-cols-[1fr_320px]"><Panel><SectionTitle title="宏观数据面板" en="OFFICIAL RAW SERIES" />{macroRows.length ? <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{macroRows.map(([key, item]) => { const last = item.rows?.[0]; const number = last ? Object.values(last).find((value) => typeof value === "number") : undefined; return <div key={key} className="rounded-md border border-agent-border bg-agent-raised p-3"><div className="flex items-center gap-2"><StatusDot status={item.available ? "complete" : "unavailable"} /><span className="font-data text-[9px] uppercase text-agent-dim">{key}</span></div><p className="mt-3 font-data text-lg text-agent-text">{number != null ? formatNumber(Number(number)) : "—"}</p><p className="mt-2 font-data text-[9px] text-agent-dim">{item.start || "—"} → {item.end || "—"} · {item.points || 0} pts</p></div>; })}</div> : <Gap title="宏观序列不可用" detail="检查 Structured Data publication 状态。" />}</Panel><Panel><SectionTitle title="缺失数据航标" en="NO SUBSTITUTION" /><div className="space-y-2">{["cn_ip", "cn_trade", "yc_cb", "人民币交叉汇率"].map((item) => <div key={item} className="rounded border border-agent-border bg-agent-raised p-3"><p className="font-data text-[10px] text-agent-amber">{item}</p><p className="mt-1 text-[10px] text-agent-dim">UNAVAILABLE · no proxy</p></div>)}</div><p className="mt-4 font-data text-[9px] text-agent-dim">CAPABILITY {capabilities?.version?.slice(0, 12) || "—"}</p></Panel></div> : null}{view === "rates" ? <RatesDrilldown /> : null}</TabsContent>
    </Tabs>
  </DashboardPage>;
}

function Secondary({ items, value, onChange }: { items: string[][]; value: string; onChange: (value: string) => void }) { return <div className="flex max-w-full gap-1 overflow-x-auto border-b border-agent-border pb-2">{items.map(([key, label]) => <button type="button" key={key} onClick={() => onChange(key)} className={`whitespace-nowrap rounded px-3 py-1.5 text-xs ${value === key ? "bg-agent-raised text-agent-mint" : "text-agent-dim hover:text-agent-text"}`}>{label}</button>)}</div>; }
function Gap({ title, detail }: { title: string; detail: string }) { return <EmptyPanel title={title} detail={detail} />; }
