"""Seed data for RPG achievements and quests."""

ACHIEVEMENTS = [
    # Trading
    {
        "id": "first_blood",
        "name": "First Blood",
        "description": "Record your first winning trade",
        "category": "trading",
        "rarity": "common",
        "icon": "",
        "criteria": {"type": "win_count", "threshold": 1},
        "xp_reward": 10,
    },
    {
        "id": "sharpshooter",
        "name": "Sharpshooter",
        "description": "Win 10 trades",
        "category": "trading",
        "rarity": "common",
        "icon": "",
        "criteria": {"type": "win_count", "threshold": 10},
        "xp_reward": 25,
    },
    {
        "id": "century",
        "name": "Century",
        "description": "Complete 100 trades",
        "category": "trading",
        "rarity": "rare",
        "icon": "",
        "criteria": {"type": "trade_count", "threshold": 100},
        "xp_reward": 50,
    },
    {
        "id": "money_maker",
        "name": "Money Maker",
        "description": "Accumulate $1,000 in total profit",
        "category": "trading",
        "rarity": "rare",
        "icon": "",
        "criteria": {"type": "profit_total", "threshold": 1000},
        "xp_reward": 50,
    },
    {
        "id": "whale",
        "name": "Whale",
        "description": "Accumulate $10,000 in total profit",
        "category": "trading",
        "rarity": "epic",
        "icon": "",
        "criteria": {"type": "profit_total", "threshold": 10000},
        "xp_reward": 100,
    },
    {
        "id": "win_rate_60",
        "name": "Above Average",
        "description": "Maintain 60%+ win rate over 20 trades",
        "category": "trading",
        "rarity": "rare",
        "icon": "",
        "criteria": {"type": "win_rate", "threshold": 60, "min_trades": 20},
        "xp_reward": 40,
    },
    {
        "id": "win_rate_75",
        "name": "Elite Trader",
        "description": "Maintain 75%+ win rate over 30 trades",
        "category": "trading",
        "rarity": "epic",
        "icon": "",
        "criteria": {"type": "win_rate", "threshold": 75, "min_trades": 30},
        "xp_reward": 80,
    },

    # Discipline
    {
        "id": "cool_head",
        "name": "Cool Head",
        "description": "Complete 10 trades without any rule violations",
        "category": "discipline",
        "rarity": "common",
        "icon": "",
        "criteria": {"type": "no_violations_streak", "threshold": 10},
        "xp_reward": 30,
    },
    {
        "id": "iron_discipline",
        "name": "Iron Discipline",
        "description": "Complete 30 trades without any rule violations",
        "category": "discipline",
        "rarity": "rare",
        "icon": "",
        "criteria": {"type": "no_violations_streak", "threshold": 30},
        "xp_reward": 60,
    },
    {
        "id": "risk_master",
        "name": "Risk Master",
        "description": "Set stop loss on 90%+ of your trades",
        "category": "discipline",
        "rarity": "rare",
        "icon": "",
        "criteria": {"type": "stop_loss_rate", "threshold": 90},
        "xp_reward": 40,
    },
    {
        "id": "discipline_maxed",
        "name": "Discipline Maxed",
        "description": "Reach 90+ discipline attribute",
        "category": "discipline",
        "rarity": "epic",
        "icon": "",
        "criteria": {"type": "attribute_score", "attribute": "discipline", "threshold": 90},
        "xp_reward": 80,
    },

    # Streaks
    {
        "id": "diamond_hands",
        "name": "Diamond Hands",
        "description": "Win 5 trades in a row",
        "category": "streaks",
        "rarity": "rare",
        "icon": "",
        "criteria": {"type": "win_streak", "threshold": 5},
        "xp_reward": 40,
    },
    {
        "id": "unstoppable",
        "name": "Unstoppable",
        "description": "Win 10 trades in a row",
        "category": "streaks",
        "rarity": "epic",
        "icon": "",
        "criteria": {"type": "win_streak", "threshold": 10},
        "xp_reward": 80,
    },
    {
        "id": "journal_keeper",
        "name": "Journal Keeper",
        "description": "Journal with notes for 7 consecutive days",
        "category": "streaks",
        "rarity": "rare",
        "icon": "",
        "criteria": {"type": "daily_journal", "threshold": 7},
        "xp_reward": 50,
    },
    {
        "id": "journal_master",
        "name": "Journal Master",
        "description": "Journal with notes for 30 consecutive days",
        "category": "streaks",
        "rarity": "epic",
        "icon": "",
        "criteria": {"type": "daily_journal", "threshold": 30},
        "xp_reward": 100,
    },

    # Milestones
    {
        "id": "level_10",
        "name": "Rising Star",
        "description": "Reach level 10",
        "category": "milestones",
        "rarity": "common",
        "icon": "",
        "criteria": {"type": "level_reached", "threshold": 10},
        "xp_reward": 20,
    },
    {
        "id": "level_20",
        "name": "Silver Rank",
        "description": "Reach level 20 and Silver rank",
        "category": "milestones",
        "rarity": "rare",
        "icon": "",
        "criteria": {"type": "level_reached", "threshold": 20},
        "xp_reward": 40,
    },
    {
        "id": "level_40",
        "name": "Gold Standard",
        "description": "Reach level 40 and Gold rank",
        "category": "milestones",
        "rarity": "epic",
        "icon": "",
        "criteria": {"type": "level_reached", "threshold": 40},
        "xp_reward": 80,
    },
    {
        "id": "level_80",
        "name": "Diamond Legend",
        "description": "Reach level 80 and Diamond rank",
        "category": "milestones",
        "rarity": "legendary",
        "icon": "",
        "criteria": {"type": "level_reached", "threshold": 80},
        "xp_reward": 200,
    },
    {
        "id": "five_hundred",
        "name": "Veteran",
        "description": "Complete 500 trades",
        "category": "milestones",
        "rarity": "epic",
        "icon": "",
        "criteria": {"type": "trade_count", "threshold": 500},
        "xp_reward": 100,
    },
]

QUESTS = [
    # Daily quests
    {
        "id": "daily_journal_2",
        "name": "Daily Scribe",
        "description": "Record 2 trades with notes today",
        "quest_type": "daily",
        "criteria": {"type": "journal_with_notes", "count": 2},
        "xp_reward": 15,
    },
    {
        "id": "daily_trade_1",
        "name": "Active Trader",
        "description": "Complete at least 1 trade today",
        "quest_type": "daily",
        "criteria": {"type": "trade_count", "count": 1},
        "xp_reward": 10,
    },
    {
        "id": "daily_stop_loss",
        "name": "Safety First",
        "description": "Set stop loss on all trades today (minimum 1)",
        "quest_type": "daily",
        "criteria": {"type": "stop_loss_set", "count": 1},
        "xp_reward": 15,
    },
    {
        "id": "daily_clean",
        "name": "Clean Sheet",
        "description": "Complete 2 trades with no rule violations",
        "quest_type": "daily",
        "criteria": {"type": "no_violations", "count": 2},
        "xp_reward": 20,
    },

    # Weekly quests
    {
        "id": "weekly_win_rate",
        "name": "Weekly Champion",
        "description": "Maintain 60%+ win rate this week (min 5 trades)",
        "quest_type": "weekly",
        "criteria": {"type": "win_rate", "threshold": 60, "count": 60},
        "xp_reward": 50,
    },
    {
        "id": "weekly_trades_10",
        "name": "Busy Week",
        "description": "Complete 10 trades this week",
        "quest_type": "weekly",
        "criteria": {"type": "trade_count", "count": 10},
        "xp_reward": 30,
    },
    {
        "id": "weekly_journal_5",
        "name": "Weekly Review",
        "description": "Record 5 trades with notes this week",
        "quest_type": "weekly",
        "criteria": {"type": "journal_with_notes", "count": 5},
        "xp_reward": 35,
    },
    {
        "id": "weekly_discipline",
        "name": "Disciplined Week",
        "description": "Complete 7 trades with no rule violations this week",
        "quest_type": "weekly",
        "criteria": {"type": "no_violations", "count": 7},
        "xp_reward": 45,
    },

    # Special quests
    {
        "id": "special_perfect_day",
        "name": "Perfect Day",
        "description": "Win all trades in a single day (minimum 3)",
        "quest_type": "special",
        "criteria": {"type": "win_rate", "threshold": 100, "count": 100},
        "xp_reward": 60,
    },
    {
        "id": "special_comeback",
        "name": "The Comeback",
        "description": "Win 3 trades after a losing streak of 3+",
        "quest_type": "special",
        "criteria": {"type": "win_streak", "count": 3},
        "xp_reward": 50,
    },
]
