"use client";

import { Anchor, BookOpen, Loader2, Plus, Save } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Panel, PanelGroup, PanelResizeHandle } from "react-resizable-panels";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { agentPlatformApi, type ResearchThesis } from "@/lib/api/agent-platform";

const LAST = "keeltrader:thesis:last-selection";
export default function ThesesPage() {
  const [items, setItems] = useState<ResearchThesis[]>([]), [selected, setSelected] = useState<ResearchThesis | null>(null), [loading, setLoading] = useState(true), [creating, setCreating] = useState(false);
  const load = useCallback(async (restore = false) => { const result = await agentPlatformApi.theses(); setItems(result.items); setLoading(false); if (restore) { const query = new URLSearchParams(window.location.search).get("thesis"); const remembered = query || window.localStorage.getItem(LAST); if (remembered && result.items.some((item) => item.id === remembered)) setSelected(await agentPlatformApi.thesis(remembered)); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(true).catch((error) => { setLoading(false); toast.error(error instanceof Error ? error.message : "论点中心加载失败"); }), 0); return () => window.clearTimeout(timer); }, [load]);
  const choose = async (id: string) => { setSelected(await agentPlatformApi.thesis(id)); window.localStorage.setItem(LAST, id); setCreating(false); };
  return <main className="flex h-full min-h-0 flex-col bg-background p-4 md:p-7"><header className="flex flex-wrap items-end justify-between gap-4 border-b pb-5"><div><p className="font-data text-[9px] uppercase tracking-[.24em] text-[hsl(var(--copper-foreground))]">Research logbook</p><h1 className="mt-2 font-display text-3xl font-semibold">论点航海日志</h1><p className="mt-2 text-xs text-muted-foreground">每次人工确认生成不可变版本；证据分支持、冲突与证伪，不计算置信分。</p></div><Button onClick={() => { setCreating(true); setSelected(null); }}><Plus className="mr-2 h-4 w-4" />建立草稿</Button></header>
    {loading ? <div className="grid flex-1 place-items-center"><Loader2 className="h-6 w-6 animate-spin" /></div> : <><PanelGroup direction="horizontal" autoSaveId="thesis-logbook" className="mt-5 hidden min-h-0 flex-1 overflow-hidden rounded-2xl border bg-card/60 md:flex"><Panel defaultSize={28} minSize={20} maxSize={42}><ThesisStream items={items} selectedId={selected?.id} onChoose={choose} /></Panel><PanelResizeHandle className="w-1 bg-border hover:bg-[hsl(var(--copper))]" /><Panel minSize={45}>{creating ? <ThesisForm onSaved={(item) => { void load(); void choose(item.id); }} /> : <ThesisDetail key={selected?.id || "overview"} item={selected} onSaved={(item) => { setSelected(item); void load(); }} />}</Panel></PanelGroup><div className="mt-5 space-y-4 md:hidden"><ThesisStream items={items} selectedId={selected?.id} onChoose={choose} />{creating ? <ThesisForm onSaved={(item) => { void load(); void choose(item.id); }} /> : <ThesisDetail key={`mobile-${selected?.id || "overview"}`} item={selected} onSaved={(item) => { setSelected(item); void load(); }} />}</div></>}
  </main>;
}
function ThesisStream({ items, selectedId, onChoose }: { items: ResearchThesis[]; selectedId?: string; onChoose: (id: string) => Promise<void> }) { return <aside className="h-full overflow-y-auto p-3"><p className="px-2 py-2 text-[10px] font-semibold uppercase tracking-[.18em] text-muted-foreground">论点流 · 最近更新</p>{items.map((item) => <button key={item.id} onClick={() => void onChoose(item.id)} className={`mb-2 w-full rounded-xl border p-3 text-left ${selectedId === item.id ? "border-[hsl(var(--copper))] bg-[hsl(var(--accent)/.12)]" : "bg-background/60 hover:bg-secondary"}`}><span className="text-xs font-medium">{item.title}</span><span className="mt-2 flex justify-between font-data text-[9px] text-muted-foreground"><span>{item.status} · v{item.current_version}</span><span>{new Date(item.updated_at).toLocaleDateString("zh-CN")}</span></span></button>)}{!items.length && <div className="m-2 rounded-xl border border-dashed p-8 text-center text-xs text-muted-foreground">尚无论点。建立草稿后再由你决定是否激活。</div>}</aside>; }
function ThesisDetail({ item, onSaved }: { item: ResearchThesis | null; onSaved: (item: ResearchThesis) => void }) { const [text, setText] = useState(item?.thesis || ""), [status, setStatus] = useState(item?.status || "draft"); if (!item) return <section className="grid h-full min-h-[420px] place-items-center p-8 text-center"><div><Anchor className="mx-auto h-9 w-9 text-[hsl(var(--copper-foreground))]" /><h2 className="mt-4 font-display text-2xl font-semibold">选择一条论点日志</h2><p className="mt-2 text-xs text-muted-foreground">没有上次明确选择时保持总览，不自动打开第一条。</p></div></section>; const save = async () => onSaved(await agentPlatformApi.updateThesis(item.id, { thesis: text, status } as Partial<ResearchThesis>)); return <section className="h-full overflow-y-auto p-5 md:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-data text-[9px] text-muted-foreground">{item.subject_type} · {item.subject_key} · v{item.current_version}</p><h2 className="mt-2 font-display text-2xl font-semibold">{item.title}</h2></div><select value={status} onChange={(e) => setStatus(e.target.value as ResearchThesis["status"])} className="rounded-lg border bg-background px-3 py-2 text-xs">{["draft","active","challenged","invalidated","closed"].map((value) => <option key={value}>{value}</option>)}</select></div><Textarea className="mt-5 min-h-40" value={text} onChange={(e) => setText(e.target.value)} /><Button className="mt-3" onClick={() => void save()}><Save className="mr-2 h-4 w-4" />确认并生成新版本</Button><div className="mt-7 grid gap-5 xl:grid-cols-2"><section><h3 className="font-display text-lg font-semibold">证据日志</h3><div className="mt-3 space-y-2">{item.evidence?.map((e) => <article key={`${e.stance}-${e.source_type}-${e.source_id}`} className="rounded-xl border bg-background/60 p-3"><p className="text-xs font-medium">{e.stance} · {e.source_type}</p><p className="mt-2 break-all font-data text-[9px] text-muted-foreground">{e.source_id}</p></article>) || null}</div></section><section><h3 className="font-display text-lg font-semibold">不可变版本</h3><div className="mt-3 space-y-3">{item.versions?.map((v) => <article key={v.id} className="border-l pl-3"><p className="text-xs font-medium">版本 {v.version}</p><p className="mt-1 font-data text-[9px] text-muted-foreground">{new Date(v.created_at).toLocaleString("zh-CN")} · 变化字段 {Object.keys(v.diff).length}</p></article>)}</div></section></div></section>; }
function ThesisForm({ onSaved }: { onSaved: (item: ResearchThesis) => void }) { const [title, setTitle] = useState(""), [subject, setSubject] = useState(""), [text, setText] = useState(""); const save = async () => { if (!title.trim() || !subject.trim() || !text.trim()) return toast.error("请填写标题、研究对象和可证伪论点"); onSaved(await agentPlatformApi.createThesis({ title, subject_type: "manual", subject_key: subject, thesis: text, status: "draft", catalysts: [], falsifiers: [] })); }; return <section className="h-full overflow-y-auto p-5 md:p-7"><BookOpen className="h-7 w-7 text-[hsl(var(--copper-foreground))]" /><h2 className="mt-3 font-display text-2xl font-semibold">建立论点草稿</h2><p className="mt-2 text-xs text-muted-foreground">创建后仍是草稿，不会自动形成正式结论。</p><div className="mt-5 space-y-3"><Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="论点标题" /><Input value={subject} onChange={(e) => setSubject(e.target.value)} placeholder="公司、资产或研究对象" /><Textarea className="min-h-40" value={text} onChange={(e) => setText(e.target.value)} placeholder="写下可验证、可证伪的论点…" /><Button onClick={() => void save()}>保存草稿</Button></div></section>; }
